<?php

namespace QuizBundle\Repository;

/**
 * roundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class roundRepository extends \Doctrine\ORM\EntityRepository
{


}
