quiz:
    resource: "@QuizBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix:   /appBundle

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"